[package]
name = "twello"
version = "0.1.0"
authors = ["kevin larrabee <echo1+git@dvnl.net>"]
edition = "2018"

[dependencies]
diesel = { version = "1.3.3", features = ["postgres"] }
dotenv = "0.10.1"
